"""Dataset-card building and the publishing port.

The :class:`DatasetCard` is a pure value object that renders a Hugging Face
dataset card (YAML frontmatter + Markdown body). It deliberately carries no
fabricated metrics — only provenance and license metadata known at assembly time
— in line with the integrity layer of the closure contract. The
:class:`DatasetPublisher` port is implemented by an infrastructure adapter
(``huggingface_hub``) so the application layer never imports it directly.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol, runtime_checkable

from psalm.domain.data.licenses import SourceManifest


@dataclass(frozen=True)
class DatasetCard:
    """A Hugging Face dataset card rendered from known provenance metadata."""

    name: str
    pretty_name: str
    license_spdx: str
    summary: str
    languages: tuple[str, ...] = ("sa",)
    tags: tuple[str, ...] = ()
    sources: tuple[SourceManifest, ...] = field(default_factory=tuple)

    def to_markdown(self) -> str:
        """Render the card as frontmatter + body. Reproducible and metric-free."""
        lang_block = "\n".join(f"  - {lang}" for lang in self.languages)
        tag_block = "\n".join(f"  - {tag}" for tag in self.tags)
        frontmatter = [
            "---",
            f"pretty_name: {self.pretty_name}",
            "language:",
            lang_block,
            f"license: {self.license_spdx}",
        ]
        if self.tags:
            frontmatter += ["tags:", tag_block]
        frontmatter.append("---")

        body = [
            f"# {self.pretty_name}",
            "",
            self.summary,
            "",
            "## Sources",
            "",
        ]
        if self.sources:
            body.append("| Source | License | Docs | Tokens |")
            body.append("| --- | --- | --- | --- |")
            for s in self.sources:
                body.append(f"| {s.name} | {s.license.spdx} | {s.n_docs} | {s.n_tokens} |")
        else:
            body.append("_No sources recorded yet._")
        body += [
            "",
            "## Provenance",
            "",
            "Generated by the PSALM data engine. License cleanliness is enforced "
            "before publication; see the source table above.",
        ]
        return "\n".join([*frontmatter, "", *body, ""])


@runtime_checkable
class DatasetPublisher(Protocol):
    """Publishes a local dataset directory + card to a hub repository."""

    def publish(
        self,
        repo_id: str,
        local_dir: Path,
        card: DatasetCard,
        *,
        private: bool = False,
    ) -> str: ...
