"""Re-match the Dyck control to **real Vidyut-realized** sentence-level statistics.

This is the no-shortcut, no-proxy harness (workstream ``dyck-control`` / ADR-0025,
ADR-0033). Targets are computed *directly* from a realized Sanskrit corpus JSONL
(the ``text`` field of every line), not from a cached Saṃsādhanī stats blob. The
default corpus is ``data/fixtures/paninian_v1.jsonl`` produced by the
``vidyut-realize`` workstream (``VidyutFrameRealizer``).

It grid-searches :class:`DyckConfig` to minimise the DEFAULT_KEYS distance to the
realized targets, runs the hard equivalence gate, pins the Hu et al. replication
config (ADR-0025) for reference, and writes:

* ``configs/data/dyck-matched.yaml``      -- the matched config (training consumes this)
* ``docs/data/dyck-match-result.json``    -- machine-readable result
* ``docs/data/dyck-match-report.md``      -- human-readable report

    uv run python scripts/dyck_recompute_match.py
    uv run python scripts/dyck_recompute_match.py --realized-corpus data/fixtures/paninian_v1.jsonl
"""

from __future__ import annotations

import argparse
import hashlib
import json
from collections.abc import Iterable
from datetime import UTC, datetime
from pathlib import Path

from psalm.domain.data.diversity import summarize
from psalm.domain.data.dyck import DyckConfig, generate_corpus, hu_replication_config
from psalm.domain.data.matching import (
    DEFAULT_KEYS,
    assert_statistically_equivalent,
    byte_length_distance,
    byte_length_histogram,
    match_dyck,
    stat_distance,
)

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "docs" / "data"
CONFIGS = ROOT / "configs" / "data"
DEFAULT_CORPUS = ROOT / "data" / "fixtures" / "paninian_v1.jsonl"
REPORT = DATA / "dyck-match-report.md"
RESULT_JSON = DATA / "dyck-match-result.json"

# Hard equivalence threshold on DEFAULT_KEYS (Euclidean over TTR + bi/tri-gram entropy).
MAX_DEFAULT_DISTANCE = 0.05

# Grid for surface-stat matching. Brackets the realized-corpus optimum (high
# bracket_types -> low TTR matching the controlled Sanskrit lexicon; entropy
# tracked via depth/length) plus coarse neighbours so the search is honest.
_CANDIDATES: tuple[DyckConfig, ...] = tuple(
    DyckConfig(bracket_types=bt, max_depth=md, n_shuffles=ns, min_len=8, max_len=ml)
    for bt in (8, 16, 24, 35)
    for md in (8, 12, 16)
    for ns in (1, 2)
    for ml in (96, 128, 192)
)


def _read_realized_texts(path: Path) -> list[str]:
    """Return the realized surface ``text`` of every line in a corpus JSONL."""
    texts: list[str] = []
    with path.open(encoding="utf-8") as handle:
        for raw in handle:
            raw = raw.strip()
            if not raw:
                continue
            obj = json.loads(raw)
            text = obj.get("text")
            if not isinstance(text, str) or not text:
                raise ValueError(f"line missing non-empty 'text': {raw[:80]!r}")
            texts.append(text)
    if not texts:
        raise ValueError(f"no realized sentences in {path}")
    return texts


def _targets_from_corpus(texts: Iterable[str]) -> dict[str, float]:
    stats = summarize(list(texts))
    return {k: float(stats[k]) for k in DEFAULT_KEYS}


def _cfg_dict(cfg: DyckConfig) -> dict[str, int]:
    return {
        "bracket_types": cfg.bracket_types,
        "max_depth": cfg.max_depth,
        "n_shuffles": cfg.n_shuffles,
        "min_len": cfg.min_len,
        "max_len": cfg.max_len,
    }


def _config_hash(cfg: DyckConfig, targets: dict[str, float]) -> str:
    """Stable short hash over the matched config + the targets it was fit to."""
    blob = json.dumps(
        {"config": _cfg_dict(cfg), "targets": targets}, sort_keys=True, separators=(",", ":")
    )
    return hashlib.sha256(blob.encode("utf-8")).hexdigest()[:12]


def _write_matched_yaml(cfg: DyckConfig, *, distance: float, source: str, digest: str) -> Path:
    CONFIGS.mkdir(parents=True, exist_ok=True)
    path = CONFIGS / f"dyck_matched_{digest}.yaml"
    lines = [
        "# Dyck control config matched to REAL Vidyut-realized sentence stats.",
        "# Generated by scripts/dyck_recompute_match.py (ADR-0025/0033); do not hand-edit.",
        f"# matched_distance (DEFAULT_KEYS): {distance:.6f} <= {MAX_DEFAULT_DISTANCE}",
        f"# target_source: {source}",
        f"# config_hash: {digest}",
        "dyck:",
        f"  bracket_types: {cfg.bracket_types}",
        f"  max_depth: {cfg.max_depth}",
        f"  n_shuffles: {cfg.n_shuffles}",
        f"  min_len: {cfg.min_len}",
        f"  max_len: {cfg.max_len}",
    ]
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--realized-corpus",
        type=Path,
        default=DEFAULT_CORPUS,
        help="JSONL of realized sentences; targets computed from each line's 'text'.",
    )
    parser.add_argument("--n", type=int, default=400, help="dyck sequences per candidate")
    parser.add_argument("--seed", type=int, default=0)
    args = parser.parse_args()

    corpus_path: Path = args.realized_corpus
    if not corpus_path.is_file():
        raise SystemExit(
            f"realized corpus not found: {corpus_path}\n"
            "Pull it from the vidyut-realize workstream, e.g.:\n"
            "  git checkout workstream/vidyut-realize -- data/fixtures/paninian_v1.jsonl"
        )
    texts = _read_realized_texts(corpus_path)
    targets = _targets_from_corpus(texts)
    real_hist = byte_length_histogram(texts, bins=16)
    source = f"{corpus_path.relative_to(ROOT)} (n={len(texts)} realized sentences)"

    matched = match_dyck(targets, _CANDIDATES, n=args.n, seed=args.seed)
    matched_corpus = generate_corpus(args.n, matched.config, args.seed)
    matched_hist = byte_length_histogram(matched_corpus, bins=16)
    # Gate on DEFAULT_KEYS only (acceptance D-match-eps). Byte-length histogram is
    # reported for transparency but is *not* a gate: Dyck uses atomic single-byte
    # symbols while Sanskrit uses multi-byte words, so their whitespace-token byte
    # lengths are non-comparable by construction. The shared tokenizer (set in the
    # measurement workstream) is where post-tokenization length parity is enforced.
    equivalence = assert_statistically_equivalent(
        matched.stats,
        targets,
        max_default_distance=MAX_DEFAULT_DISTANCE,
    )
    real_vs_matched_byte_l1 = byte_length_distance(matched_hist, real_hist)

    hu_cfg = hu_replication_config()
    hu_stats = summarize(generate_corpus(args.n, hu_cfg, args.seed))
    hu_dist = stat_distance(hu_stats, targets)

    digest = _config_hash(matched.config, targets)
    payload = {
        "generated_at": datetime.now(UTC).isoformat(),
        "baseline_source": source,
        "no_proxy": True,
        "n_realized_sentences": len(texts),
        "config_hash": digest,
        "targets": targets,
        "max_default_distance": MAX_DEFAULT_DISTANCE,
        "matched_config": _cfg_dict(matched.config),
        "matched_distance": matched.distance,
        "matched_stats": matched.stats,
        "matched_byte_hist_l1_vs_real": real_vs_matched_byte_l1,
        "byte_hist_is_gated": False,
        "equivalence_passed": equivalence.passed,
        "hu_replication_config": _cfg_dict(hu_cfg),
        "hu_replication_distance": hu_dist,
        "hu_replication_stats": hu_stats,
    }
    DATA.mkdir(parents=True, exist_ok=True)
    RESULT_JSON.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    matched_yaml = _write_matched_yaml(
        matched.config, distance=matched.distance, source=source, digest=digest
    )

    verdict = "PASS" if equivalence.passed else "FAIL"
    report = f"""# Dyck surface-stat match report (real Vidyut-realized targets)

Generated: `{payload["generated_at"]}`

**Targets computed directly from realized sentences (no proxy, no cached blob).**
Source: `{source}`

## Targets (DEFAULT_KEYS)

| Key | Value |
|-----|-------|
| type_token_ratio | {targets["type_token_ratio"]:.6f} |
| bigram_entropy | {targets["bigram_entropy"]:.6f} |
| trigram_entropy | {targets["trigram_entropy"]:.6f} |

## Best grid match (H1 fairness) — gate {verdict}

| Field | Value |
|-------|-------|
| bracket_types | {matched.config.bracket_types} |
| max_depth | {matched.config.max_depth} |
| n_shuffles | {matched.config.n_shuffles} |
| min_len | {matched.config.min_len} |
| max_len | {matched.config.max_len} |
| DEFAULT_KEYS distance | {matched.distance:.6f} |
| threshold | {MAX_DEFAULT_DISTANCE} |
| L1 byte-length hist vs real corpus (informational, not gated) | {real_vs_matched_byte_l1:.6f} |

Matched corpus stats: `{json.dumps(matched.stats)}`

Matched config written to `{matched_yaml.relative_to(ROOT)}` (config_hash `{digest}`).

## Hu et al. replication config (ADR-0025)

Pinned `hu_replication_config()`: k={hu_cfg.bracket_types}, max_depth={hu_cfg.max_depth},
n_shuffles={hu_cfg.n_shuffles}, max_len={hu_cfg.max_len} (reference; not the H1 match).

| Metric | Value |
|--------|-------|
| Distance to targets (DEFAULT_KEYS) | {hu_dist:.6f} |

Hu replication stats: `{json.dumps(hu_stats)}`

## Artifacts

- Machine-readable: `docs/data/dyck-match-result.json`
- Matched training config: `{matched_yaml.relative_to(ROOT)}`
"""
    REPORT.write_text(report, encoding="utf-8")
    print(f"Wrote {REPORT}")
    print(f"Wrote {RESULT_JSON}")
    print(f"Wrote {matched_yaml}")
    print(f"match distance={matched.distance:.6f} threshold={MAX_DEFAULT_DISTANCE} -> {verdict}")
    if not equivalence.passed:
        raise SystemExit("equivalence gate FAILED: widen the grid or revisit targets")


if __name__ == "__main__":
    main()
